#!/usr/bin/env zsh
set -ev
ARCHIVES_DIR=archives
NASA_SHAPEFILES_FILE_NAME=2024eclipse_shapefiles.zip
NASA_SHAPEFILES_FILE=$ARCHIVES_DIR/$NASA_SHAPEFILES_FILE_NAME
NASA_SHAPEFILES_FILE_URL=https://svs.gsfc.nasa.gov/vis/a000000/a005000/a005073/$NASA_SHAPEFILES_FILE_NAME
NASA_SHAPEFILES_DIR=$NASA_SHAPEFILES_FILE.d

if [ ! -d $NASA_SHAPEFILES_DIR ] ; then
  mkdir -p $NASA_SHAPEFILES_DIR
  curl -sv -L $NASA_SHAPEFILES_FILE_URL -o $NASA_SHAPEFILES_FILE
  unzip -d $NASA_SHAPEFILES_DIR $NASA_SHAPEFILES_FILE
fi
